[project]
name = "artifical-weather-forecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.12",
    "numpy>=2.2.3",
    "openmeteo-requests>=1.3.0",
    "requests>=2.32.3",
]

[tool.basedpyright]
reportExplicitAny = false
